// Code generated by tools/gen_ast.v from libpg_query/protobuf/pg_query.proto
// DO NOT EDIT.
#ifndef PG_QUERY_AST_C_H
#define PG_QUERY_AST_C_H

#include <stdint.h>
#include <stddef.h>

// V ABI compatible types for direct struct population
typedef struct { unsigned char* str; int len; int is_lit; } VString;
typedef struct { void* data; int offset; int len; int cap; int flags; int element_size; } VArray;

// Forward declarations
typedef struct V_Integer V_Integer;
typedef struct V_Float V_Float;
typedef struct V_Boolean V_Boolean;
typedef struct V_String V_String;
typedef struct V_BitString V_BitString;
typedef struct V_List V_List;
typedef struct V_OidList V_OidList;
typedef struct V_IntList V_IntList;
typedef struct V_AConst V_AConst;
typedef struct V_Alias V_Alias;
typedef struct V_RangeVar V_RangeVar;
typedef struct V_TableFunc V_TableFunc;
typedef struct V_IntoClause V_IntoClause;
typedef struct V_Var V_Var;
typedef struct V_Param V_Param;
typedef struct V_Aggref V_Aggref;
typedef struct V_GroupingFunc V_GroupingFunc;
typedef struct V_WindowFunc V_WindowFunc;
typedef struct V_WindowFuncRunCondition V_WindowFuncRunCondition;
typedef struct V_MergeSupportFunc V_MergeSupportFunc;
typedef struct V_SubscriptingRef V_SubscriptingRef;
typedef struct V_FuncExpr V_FuncExpr;
typedef struct V_NamedArgExpr V_NamedArgExpr;
typedef struct V_OpExpr V_OpExpr;
typedef struct V_DistinctExpr V_DistinctExpr;
typedef struct V_NullIfExpr V_NullIfExpr;
typedef struct V_ScalarArrayOpExpr V_ScalarArrayOpExpr;
typedef struct V_BoolExpr V_BoolExpr;
typedef struct V_SubLink V_SubLink;
typedef struct V_SubPlan V_SubPlan;
typedef struct V_AlternativeSubPlan V_AlternativeSubPlan;
typedef struct V_FieldSelect V_FieldSelect;
typedef struct V_FieldStore V_FieldStore;
typedef struct V_RelabelType V_RelabelType;
typedef struct V_CoerceViaIO V_CoerceViaIO;
typedef struct V_ArrayCoerceExpr V_ArrayCoerceExpr;
typedef struct V_ConvertRowtypeExpr V_ConvertRowtypeExpr;
typedef struct V_CollateExpr V_CollateExpr;
typedef struct V_CaseExpr V_CaseExpr;
typedef struct V_CaseWhen V_CaseWhen;
typedef struct V_CaseTestExpr V_CaseTestExpr;
typedef struct V_ArrayExpr V_ArrayExpr;
typedef struct V_RowExpr V_RowExpr;
typedef struct V_RowCompareExpr V_RowCompareExpr;
typedef struct V_CoalesceExpr V_CoalesceExpr;
typedef struct V_MinMaxExpr V_MinMaxExpr;
typedef struct V_SQLValueFunction V_SQLValueFunction;
typedef struct V_XmlExpr V_XmlExpr;
typedef struct V_JsonFormat V_JsonFormat;
typedef struct V_JsonReturning V_JsonReturning;
typedef struct V_JsonValueExpr V_JsonValueExpr;
typedef struct V_JsonConstructorExpr V_JsonConstructorExpr;
typedef struct V_JsonIsPredicate V_JsonIsPredicate;
typedef struct V_JsonBehavior V_JsonBehavior;
typedef struct V_JsonExpr V_JsonExpr;
typedef struct V_JsonTablePath V_JsonTablePath;
typedef struct V_JsonTablePathScan V_JsonTablePathScan;
typedef struct V_JsonTableSiblingJoin V_JsonTableSiblingJoin;
typedef struct V_NullTest V_NullTest;
typedef struct V_BooleanTest V_BooleanTest;
typedef struct V_MergeAction V_MergeAction;
typedef struct V_CoerceToDomain V_CoerceToDomain;
typedef struct V_CoerceToDomainValue V_CoerceToDomainValue;
typedef struct V_SetToDefault V_SetToDefault;
typedef struct V_CurrentOfExpr V_CurrentOfExpr;
typedef struct V_NextValueExpr V_NextValueExpr;
typedef struct V_InferenceElem V_InferenceElem;
typedef struct V_TargetEntry V_TargetEntry;
typedef struct V_RangeTblRef V_RangeTblRef;
typedef struct V_JoinExpr V_JoinExpr;
typedef struct V_FromExpr V_FromExpr;
typedef struct V_OnConflictExpr V_OnConflictExpr;
typedef struct V_Query V_Query;
typedef struct V_TypeName V_TypeName;
typedef struct V_ColumnRef V_ColumnRef;
typedef struct V_ParamRef V_ParamRef;
typedef struct V_AExpr V_AExpr;
typedef struct V_TypeCast V_TypeCast;
typedef struct V_CollateClause V_CollateClause;
typedef struct V_RoleSpec V_RoleSpec;
typedef struct V_FuncCall V_FuncCall;
typedef struct V_AStar V_AStar;
typedef struct V_AIndices V_AIndices;
typedef struct V_AIndirection V_AIndirection;
typedef struct V_AArrayExpr V_AArrayExpr;
typedef struct V_ResTarget V_ResTarget;
typedef struct V_MultiAssignRef V_MultiAssignRef;
typedef struct V_SortBy V_SortBy;
typedef struct V_WindowDef V_WindowDef;
typedef struct V_RangeSubselect V_RangeSubselect;
typedef struct V_RangeFunction V_RangeFunction;
typedef struct V_RangeTableFunc V_RangeTableFunc;
typedef struct V_RangeTableFuncCol V_RangeTableFuncCol;
typedef struct V_RangeTableSample V_RangeTableSample;
typedef struct V_ColumnDef V_ColumnDef;
typedef struct V_TableLikeClause V_TableLikeClause;
typedef struct V_IndexElem V_IndexElem;
typedef struct V_DefElem V_DefElem;
typedef struct V_LockingClause V_LockingClause;
typedef struct V_XmlSerialize V_XmlSerialize;
typedef struct V_PartitionElem V_PartitionElem;
typedef struct V_PartitionSpec V_PartitionSpec;
typedef struct V_PartitionBoundSpec V_PartitionBoundSpec;
typedef struct V_PartitionRangeDatum V_PartitionRangeDatum;
typedef struct V_SinglePartitionSpec V_SinglePartitionSpec;
typedef struct V_PartitionCmd V_PartitionCmd;
typedef struct V_RangeTblEntry V_RangeTblEntry;
typedef struct V_RTEPermissionInfo V_RTEPermissionInfo;
typedef struct V_RangeTblFunction V_RangeTblFunction;
typedef struct V_TableSampleClause V_TableSampleClause;
typedef struct V_WithCheckOption V_WithCheckOption;
typedef struct V_SortGroupClause V_SortGroupClause;
typedef struct V_GroupingSet V_GroupingSet;
typedef struct V_WindowClause V_WindowClause;
typedef struct V_RowMarkClause V_RowMarkClause;
typedef struct V_WithClause V_WithClause;
typedef struct V_InferClause V_InferClause;
typedef struct V_OnConflictClause V_OnConflictClause;
typedef struct V_CTESearchClause V_CTESearchClause;
typedef struct V_CTECycleClause V_CTECycleClause;
typedef struct V_CommonTableExpr V_CommonTableExpr;
typedef struct V_MergeWhenClause V_MergeWhenClause;
typedef struct V_TriggerTransition V_TriggerTransition;
typedef struct V_JsonOutput V_JsonOutput;
typedef struct V_JsonArgument V_JsonArgument;
typedef struct V_JsonFuncExpr V_JsonFuncExpr;
typedef struct V_JsonTablePathSpec V_JsonTablePathSpec;
typedef struct V_JsonTable V_JsonTable;
typedef struct V_JsonTableColumn V_JsonTableColumn;
typedef struct V_JsonKeyValue V_JsonKeyValue;
typedef struct V_JsonParseExpr V_JsonParseExpr;
typedef struct V_JsonScalarExpr V_JsonScalarExpr;
typedef struct V_JsonSerializeExpr V_JsonSerializeExpr;
typedef struct V_JsonObjectConstructor V_JsonObjectConstructor;
typedef struct V_JsonArrayConstructor V_JsonArrayConstructor;
typedef struct V_JsonArrayQueryConstructor V_JsonArrayQueryConstructor;
typedef struct V_JsonAggConstructor V_JsonAggConstructor;
typedef struct V_JsonObjectAgg V_JsonObjectAgg;
typedef struct V_JsonArrayAgg V_JsonArrayAgg;
typedef struct V_RawStmt V_RawStmt;
typedef struct V_InsertStmt V_InsertStmt;
typedef struct V_DeleteStmt V_DeleteStmt;
typedef struct V_UpdateStmt V_UpdateStmt;
typedef struct V_MergeStmt V_MergeStmt;
typedef struct V_SelectStmt V_SelectStmt;
typedef struct V_SetOperationStmt V_SetOperationStmt;
typedef struct V_ReturnStmt V_ReturnStmt;
typedef struct V_PLAssignStmt V_PLAssignStmt;
typedef struct V_CreateSchemaStmt V_CreateSchemaStmt;
typedef struct V_AlterTableStmt V_AlterTableStmt;
typedef struct V_ReplicaIdentityStmt V_ReplicaIdentityStmt;
typedef struct V_AlterTableCmd V_AlterTableCmd;
typedef struct V_AlterCollationStmt V_AlterCollationStmt;
typedef struct V_AlterDomainStmt V_AlterDomainStmt;
typedef struct V_GrantStmt V_GrantStmt;
typedef struct V_ObjectWithArgs V_ObjectWithArgs;
typedef struct V_AccessPriv V_AccessPriv;
typedef struct V_GrantRoleStmt V_GrantRoleStmt;
typedef struct V_AlterDefaultPrivilegesStmt V_AlterDefaultPrivilegesStmt;
typedef struct V_CopyStmt V_CopyStmt;
typedef struct V_VariableSetStmt V_VariableSetStmt;
typedef struct V_VariableShowStmt V_VariableShowStmt;
typedef struct V_CreateStmt V_CreateStmt;
typedef struct V_Constraint V_Constraint;
typedef struct V_CreateTableSpaceStmt V_CreateTableSpaceStmt;
typedef struct V_DropTableSpaceStmt V_DropTableSpaceStmt;
typedef struct V_AlterTableSpaceOptionsStmt V_AlterTableSpaceOptionsStmt;
typedef struct V_AlterTableMoveAllStmt V_AlterTableMoveAllStmt;
typedef struct V_CreateExtensionStmt V_CreateExtensionStmt;
typedef struct V_AlterExtensionStmt V_AlterExtensionStmt;
typedef struct V_AlterExtensionContentsStmt V_AlterExtensionContentsStmt;
typedef struct V_CreateFdwStmt V_CreateFdwStmt;
typedef struct V_AlterFdwStmt V_AlterFdwStmt;
typedef struct V_CreateForeignServerStmt V_CreateForeignServerStmt;
typedef struct V_AlterForeignServerStmt V_AlterForeignServerStmt;
typedef struct V_CreateForeignTableStmt V_CreateForeignTableStmt;
typedef struct V_CreateUserMappingStmt V_CreateUserMappingStmt;
typedef struct V_AlterUserMappingStmt V_AlterUserMappingStmt;
typedef struct V_DropUserMappingStmt V_DropUserMappingStmt;
typedef struct V_ImportForeignSchemaStmt V_ImportForeignSchemaStmt;
typedef struct V_CreatePolicyStmt V_CreatePolicyStmt;
typedef struct V_AlterPolicyStmt V_AlterPolicyStmt;
typedef struct V_CreateAmStmt V_CreateAmStmt;
typedef struct V_CreateTrigStmt V_CreateTrigStmt;
typedef struct V_CreateEventTrigStmt V_CreateEventTrigStmt;
typedef struct V_AlterEventTrigStmt V_AlterEventTrigStmt;
typedef struct V_CreatePLangStmt V_CreatePLangStmt;
typedef struct V_CreateRoleStmt V_CreateRoleStmt;
typedef struct V_AlterRoleStmt V_AlterRoleStmt;
typedef struct V_AlterRoleSetStmt V_AlterRoleSetStmt;
typedef struct V_DropRoleStmt V_DropRoleStmt;
typedef struct V_CreateSeqStmt V_CreateSeqStmt;
typedef struct V_AlterSeqStmt V_AlterSeqStmt;
typedef struct V_DefineStmt V_DefineStmt;
typedef struct V_CreateDomainStmt V_CreateDomainStmt;
typedef struct V_CreateOpClassStmt V_CreateOpClassStmt;
typedef struct V_CreateOpClassItem V_CreateOpClassItem;
typedef struct V_CreateOpFamilyStmt V_CreateOpFamilyStmt;
typedef struct V_AlterOpFamilyStmt V_AlterOpFamilyStmt;
typedef struct V_DropStmt V_DropStmt;
typedef struct V_TruncateStmt V_TruncateStmt;
typedef struct V_CommentStmt V_CommentStmt;
typedef struct V_SecLabelStmt V_SecLabelStmt;
typedef struct V_DeclareCursorStmt V_DeclareCursorStmt;
typedef struct V_ClosePortalStmt V_ClosePortalStmt;
typedef struct V_FetchStmt V_FetchStmt;
typedef struct V_IndexStmt V_IndexStmt;
typedef struct V_CreateStatsStmt V_CreateStatsStmt;
typedef struct V_StatsElem V_StatsElem;
typedef struct V_AlterStatsStmt V_AlterStatsStmt;
typedef struct V_CreateFunctionStmt V_CreateFunctionStmt;
typedef struct V_FunctionParameter V_FunctionParameter;
typedef struct V_AlterFunctionStmt V_AlterFunctionStmt;
typedef struct V_DoStmt V_DoStmt;
typedef struct V_InlineCodeBlock V_InlineCodeBlock;
typedef struct V_CallStmt V_CallStmt;
typedef struct V_CallContext V_CallContext;
typedef struct V_RenameStmt V_RenameStmt;
typedef struct V_AlterObjectDependsStmt V_AlterObjectDependsStmt;
typedef struct V_AlterObjectSchemaStmt V_AlterObjectSchemaStmt;
typedef struct V_AlterOwnerStmt V_AlterOwnerStmt;
typedef struct V_AlterOperatorStmt V_AlterOperatorStmt;
typedef struct V_AlterTypeStmt V_AlterTypeStmt;
typedef struct V_RuleStmt V_RuleStmt;
typedef struct V_NotifyStmt V_NotifyStmt;
typedef struct V_ListenStmt V_ListenStmt;
typedef struct V_UnlistenStmt V_UnlistenStmt;
typedef struct V_TransactionStmt V_TransactionStmt;
typedef struct V_CompositeTypeStmt V_CompositeTypeStmt;
typedef struct V_CreateEnumStmt V_CreateEnumStmt;
typedef struct V_CreateRangeStmt V_CreateRangeStmt;
typedef struct V_AlterEnumStmt V_AlterEnumStmt;
typedef struct V_ViewStmt V_ViewStmt;
typedef struct V_LoadStmt V_LoadStmt;
typedef struct V_CreatedbStmt V_CreatedbStmt;
typedef struct V_AlterDatabaseStmt V_AlterDatabaseStmt;
typedef struct V_AlterDatabaseRefreshCollStmt V_AlterDatabaseRefreshCollStmt;
typedef struct V_AlterDatabaseSetStmt V_AlterDatabaseSetStmt;
typedef struct V_DropdbStmt V_DropdbStmt;
typedef struct V_AlterSystemStmt V_AlterSystemStmt;
typedef struct V_ClusterStmt V_ClusterStmt;
typedef struct V_VacuumStmt V_VacuumStmt;
typedef struct V_VacuumRelation V_VacuumRelation;
typedef struct V_ExplainStmt V_ExplainStmt;
typedef struct V_CreateTableAsStmt V_CreateTableAsStmt;
typedef struct V_RefreshMatViewStmt V_RefreshMatViewStmt;
typedef struct V_CheckPointStmt V_CheckPointStmt;
typedef struct V_DiscardStmt V_DiscardStmt;
typedef struct V_LockStmt V_LockStmt;
typedef struct V_ConstraintsSetStmt V_ConstraintsSetStmt;
typedef struct V_ReindexStmt V_ReindexStmt;
typedef struct V_CreateConversionStmt V_CreateConversionStmt;
typedef struct V_CreateCastStmt V_CreateCastStmt;
typedef struct V_CreateTransformStmt V_CreateTransformStmt;
typedef struct V_PrepareStmt V_PrepareStmt;
typedef struct V_ExecuteStmt V_ExecuteStmt;
typedef struct V_DeallocateStmt V_DeallocateStmt;
typedef struct V_DropOwnedStmt V_DropOwnedStmt;
typedef struct V_ReassignOwnedStmt V_ReassignOwnedStmt;
typedef struct V_AlterTSDictionaryStmt V_AlterTSDictionaryStmt;
typedef struct V_AlterTSConfigurationStmt V_AlterTSConfigurationStmt;
typedef struct V_PublicationTable V_PublicationTable;
typedef struct V_PublicationObjSpec V_PublicationObjSpec;
typedef struct V_CreatePublicationStmt V_CreatePublicationStmt;
typedef struct V_AlterPublicationStmt V_AlterPublicationStmt;
typedef struct V_CreateSubscriptionStmt V_CreateSubscriptionStmt;
typedef struct V_AlterSubscriptionStmt V_AlterSubscriptionStmt;
typedef struct V_DropSubscriptionStmt V_DropSubscriptionStmt;
typedef struct V_ScanToken V_ScanToken;
typedef struct VNode VNode;
typedef struct V_ParseAstResult V_ParseAstResult;

// VNode tagged union (matches V sum type layout)
// Tags matching V sum type tag order
#define VNODE_TAG_ALIAS 0
#define VNODE_TAG_RANGEVAR 1
#define VNODE_TAG_TABLEFUNC 2
#define VNODE_TAG_INTOCLAUSE 3
#define VNODE_TAG_VAR 4
#define VNODE_TAG_PARAM 5
#define VNODE_TAG_AGGREF 6
#define VNODE_TAG_GROUPINGFUNC 7
#define VNODE_TAG_WINDOWFUNC 8
#define VNODE_TAG_WINDOWFUNCRUNCONDITION 9
#define VNODE_TAG_MERGESUPPORTFUNC 10
#define VNODE_TAG_SUBSCRIPTINGREF 11
#define VNODE_TAG_FUNCEXPR 12
#define VNODE_TAG_NAMEDARGEXPR 13
#define VNODE_TAG_OPEXPR 14
#define VNODE_TAG_DISTINCTEXPR 15
#define VNODE_TAG_NULLIFEXPR 16
#define VNODE_TAG_SCALARARRAYOPEXPR 17
#define VNODE_TAG_BOOLEXPR 18
#define VNODE_TAG_SUBLINK 19
#define VNODE_TAG_SUBPLAN 20
#define VNODE_TAG_ALTERNATIVESUBPLAN 21
#define VNODE_TAG_FIELDSELECT 22
#define VNODE_TAG_FIELDSTORE 23
#define VNODE_TAG_RELABELTYPE 24
#define VNODE_TAG_COERCEVIAIO 25
#define VNODE_TAG_ARRAYCOERCEEXPR 26
#define VNODE_TAG_CONVERTROWTYPEEXPR 27
#define VNODE_TAG_COLLATEEXPR 28
#define VNODE_TAG_CASEEXPR 29
#define VNODE_TAG_CASEWHEN 30
#define VNODE_TAG_CASETESTEXPR 31
#define VNODE_TAG_ARRAYEXPR 32
#define VNODE_TAG_ROWEXPR 33
#define VNODE_TAG_ROWCOMPAREEXPR 34
#define VNODE_TAG_COALESCEEXPR 35
#define VNODE_TAG_MINMAXEXPR 36
#define VNODE_TAG_SQLVALUEFUNCTION 37
#define VNODE_TAG_XMLEXPR 38
#define VNODE_TAG_JSONFORMAT 39
#define VNODE_TAG_JSONRETURNING 40
#define VNODE_TAG_JSONVALUEEXPR 41
#define VNODE_TAG_JSONCONSTRUCTOREXPR 42
#define VNODE_TAG_JSONISPREDICATE 43
#define VNODE_TAG_JSONBEHAVIOR 44
#define VNODE_TAG_JSONEXPR 45
#define VNODE_TAG_JSONTABLEPATH 46
#define VNODE_TAG_JSONTABLEPATHSCAN 47
#define VNODE_TAG_JSONTABLESIBLINGJOIN 48
#define VNODE_TAG_NULLTEST 49
#define VNODE_TAG_BOOLEANTEST 50
#define VNODE_TAG_MERGEACTION 51
#define VNODE_TAG_COERCETODOMAIN 52
#define VNODE_TAG_COERCETODOMAINVALUE 53
#define VNODE_TAG_SETTODEFAULT 54
#define VNODE_TAG_CURRENTOFEXPR 55
#define VNODE_TAG_NEXTVALUEEXPR 56
#define VNODE_TAG_INFERENCEELEM 57
#define VNODE_TAG_TARGETENTRY 58
#define VNODE_TAG_RANGETBLREF 59
#define VNODE_TAG_JOINEXPR 60
#define VNODE_TAG_FROMEXPR 61
#define VNODE_TAG_ONCONFLICTEXPR 62
#define VNODE_TAG_QUERY 63
#define VNODE_TAG_TYPENAME 64
#define VNODE_TAG_COLUMNREF 65
#define VNODE_TAG_PARAMREF 66
#define VNODE_TAG_AEXPR 67
#define VNODE_TAG_TYPECAST 68
#define VNODE_TAG_COLLATECLAUSE 69
#define VNODE_TAG_ROLESPEC 70
#define VNODE_TAG_FUNCCALL 71
#define VNODE_TAG_ASTAR 72
#define VNODE_TAG_AINDICES 73
#define VNODE_TAG_AINDIRECTION 74
#define VNODE_TAG_AARRAYEXPR 75
#define VNODE_TAG_RESTARGET 76
#define VNODE_TAG_MULTIASSIGNREF 77
#define VNODE_TAG_SORTBY 78
#define VNODE_TAG_WINDOWDEF 79
#define VNODE_TAG_RANGESUBSELECT 80
#define VNODE_TAG_RANGEFUNCTION 81
#define VNODE_TAG_RANGETABLEFUNC 82
#define VNODE_TAG_RANGETABLEFUNCCOL 83
#define VNODE_TAG_RANGETABLESAMPLE 84
#define VNODE_TAG_COLUMNDEF 85
#define VNODE_TAG_TABLELIKECLAUSE 86
#define VNODE_TAG_INDEXELEM 87
#define VNODE_TAG_DEFELEM 88
#define VNODE_TAG_LOCKINGCLAUSE 89
#define VNODE_TAG_XMLSERIALIZE 90
#define VNODE_TAG_PARTITIONELEM 91
#define VNODE_TAG_PARTITIONSPEC 92
#define VNODE_TAG_PARTITIONBOUNDSPEC 93
#define VNODE_TAG_PARTITIONRANGEDATUM 94
#define VNODE_TAG_SINGLEPARTITIONSPEC 95
#define VNODE_TAG_PARTITIONCMD 96
#define VNODE_TAG_RANGETBLENTRY 97
#define VNODE_TAG_RTEPERMISSIONINFO 98
#define VNODE_TAG_RANGETBLFUNCTION 99
#define VNODE_TAG_TABLESAMPLECLAUSE 100
#define VNODE_TAG_WITHCHECKOPTION 101
#define VNODE_TAG_SORTGROUPCLAUSE 102
#define VNODE_TAG_GROUPINGSET 103
#define VNODE_TAG_WINDOWCLAUSE 104
#define VNODE_TAG_ROWMARKCLAUSE 105
#define VNODE_TAG_WITHCLAUSE 106
#define VNODE_TAG_INFERCLAUSE 107
#define VNODE_TAG_ONCONFLICTCLAUSE 108
#define VNODE_TAG_CTESEARCHCLAUSE 109
#define VNODE_TAG_CTECYCLECLAUSE 110
#define VNODE_TAG_COMMONTABLEEXPR 111
#define VNODE_TAG_MERGEWHENCLAUSE 112
#define VNODE_TAG_TRIGGERTRANSITION 113
#define VNODE_TAG_JSONOUTPUT 114
#define VNODE_TAG_JSONARGUMENT 115
#define VNODE_TAG_JSONFUNCEXPR 116
#define VNODE_TAG_JSONTABLEPATHSPEC 117
#define VNODE_TAG_JSONTABLE 118
#define VNODE_TAG_JSONTABLECOLUMN 119
#define VNODE_TAG_JSONKEYVALUE 120
#define VNODE_TAG_JSONPARSEEXPR 121
#define VNODE_TAG_JSONSCALAREXPR 122
#define VNODE_TAG_JSONSERIALIZEEXPR 123
#define VNODE_TAG_JSONOBJECTCONSTRUCTOR 124
#define VNODE_TAG_JSONARRAYCONSTRUCTOR 125
#define VNODE_TAG_JSONARRAYQUERYCONSTRUCTOR 126
#define VNODE_TAG_JSONAGGCONSTRUCTOR 127
#define VNODE_TAG_JSONOBJECTAGG 128
#define VNODE_TAG_JSONARRAYAGG 129
#define VNODE_TAG_RAWSTMT 130
#define VNODE_TAG_INSERTSTMT 131
#define VNODE_TAG_DELETESTMT 132
#define VNODE_TAG_UPDATESTMT 133
#define VNODE_TAG_MERGESTMT 134
#define VNODE_TAG_SELECTSTMT 135
#define VNODE_TAG_SETOPERATIONSTMT 136
#define VNODE_TAG_RETURNSTMT 137
#define VNODE_TAG_PLASSIGNSTMT 138
#define VNODE_TAG_CREATESCHEMASTMT 139
#define VNODE_TAG_ALTERTABLESTMT 140
#define VNODE_TAG_REPLICAIDENTITYSTMT 141
#define VNODE_TAG_ALTERTABLECMD 142
#define VNODE_TAG_ALTERCOLLATIONSTMT 143
#define VNODE_TAG_ALTERDOMAINSTMT 144
#define VNODE_TAG_GRANTSTMT 145
#define VNODE_TAG_OBJECTWITHARGS 146
#define VNODE_TAG_ACCESSPRIV 147
#define VNODE_TAG_GRANTROLESTMT 148
#define VNODE_TAG_ALTERDEFAULTPRIVILEGESSTMT 149
#define VNODE_TAG_COPYSTMT 150
#define VNODE_TAG_VARIABLESETSTMT 151
#define VNODE_TAG_VARIABLESHOWSTMT 152
#define VNODE_TAG_CREATESTMT 153
#define VNODE_TAG_CONSTRAINT 154
#define VNODE_TAG_CREATETABLESPACESTMT 155
#define VNODE_TAG_DROPTABLESPACESTMT 156
#define VNODE_TAG_ALTERTABLESPACEOPTIONSSTMT 157
#define VNODE_TAG_ALTERTABLEMOVEALLSTMT 158
#define VNODE_TAG_CREATEEXTENSIONSTMT 159
#define VNODE_TAG_ALTEREXTENSIONSTMT 160
#define VNODE_TAG_ALTEREXTENSIONCONTENTSSTMT 161
#define VNODE_TAG_CREATEFDWSTMT 162
#define VNODE_TAG_ALTERFDWSTMT 163
#define VNODE_TAG_CREATEFOREIGNSERVERSTMT 164
#define VNODE_TAG_ALTERFOREIGNSERVERSTMT 165
#define VNODE_TAG_CREATEFOREIGNTABLESTMT 166
#define VNODE_TAG_CREATEUSERMAPPINGSTMT 167
#define VNODE_TAG_ALTERUSERMAPPINGSTMT 168
#define VNODE_TAG_DROPUSERMAPPINGSTMT 169
#define VNODE_TAG_IMPORTFOREIGNSCHEMASTMT 170
#define VNODE_TAG_CREATEPOLICYSTMT 171
#define VNODE_TAG_ALTERPOLICYSTMT 172
#define VNODE_TAG_CREATEAMSTMT 173
#define VNODE_TAG_CREATETRIGSTMT 174
#define VNODE_TAG_CREATEEVENTTRIGSTMT 175
#define VNODE_TAG_ALTEREVENTTRIGSTMT 176
#define VNODE_TAG_CREATEPLANGSTMT 177
#define VNODE_TAG_CREATEROLESTMT 178
#define VNODE_TAG_ALTERROLESTMT 179
#define VNODE_TAG_ALTERROLESETSTMT 180
#define VNODE_TAG_DROPROLESTMT 181
#define VNODE_TAG_CREATESEQSTMT 182
#define VNODE_TAG_ALTERSEQSTMT 183
#define VNODE_TAG_DEFINESTMT 184
#define VNODE_TAG_CREATEDOMAINSTMT 185
#define VNODE_TAG_CREATEOPCLASSSTMT 186
#define VNODE_TAG_CREATEOPCLASSITEM 187
#define VNODE_TAG_CREATEOPFAMILYSTMT 188
#define VNODE_TAG_ALTEROPFAMILYSTMT 189
#define VNODE_TAG_DROPSTMT 190
#define VNODE_TAG_TRUNCATESTMT 191
#define VNODE_TAG_COMMENTSTMT 192
#define VNODE_TAG_SECLABELSTMT 193
#define VNODE_TAG_DECLARECURSORSTMT 194
#define VNODE_TAG_CLOSEPORTALSTMT 195
#define VNODE_TAG_FETCHSTMT 196
#define VNODE_TAG_INDEXSTMT 197
#define VNODE_TAG_CREATESTATSSTMT 198
#define VNODE_TAG_STATSELEM 199
#define VNODE_TAG_ALTERSTATSSTMT 200
#define VNODE_TAG_CREATEFUNCTIONSTMT 201
#define VNODE_TAG_FUNCTIONPARAMETER 202
#define VNODE_TAG_ALTERFUNCTIONSTMT 203
#define VNODE_TAG_DOSTMT 204
#define VNODE_TAG_INLINECODEBLOCK 205
#define VNODE_TAG_CALLSTMT 206
#define VNODE_TAG_CALLCONTEXT 207
#define VNODE_TAG_RENAMESTMT 208
#define VNODE_TAG_ALTEROBJECTDEPENDSSTMT 209
#define VNODE_TAG_ALTEROBJECTSCHEMASTMT 210
#define VNODE_TAG_ALTEROWNERSTMT 211
#define VNODE_TAG_ALTEROPERATORSTMT 212
#define VNODE_TAG_ALTERTYPESTMT 213
#define VNODE_TAG_RULESTMT 214
#define VNODE_TAG_NOTIFYSTMT 215
#define VNODE_TAG_LISTENSTMT 216
#define VNODE_TAG_UNLISTENSTMT 217
#define VNODE_TAG_TRANSACTIONSTMT 218
#define VNODE_TAG_COMPOSITETYPESTMT 219
#define VNODE_TAG_CREATEENUMSTMT 220
#define VNODE_TAG_CREATERANGESTMT 221
#define VNODE_TAG_ALTERENUMSTMT 222
#define VNODE_TAG_VIEWSTMT 223
#define VNODE_TAG_LOADSTMT 224
#define VNODE_TAG_CREATEDBSTMT 225
#define VNODE_TAG_ALTERDATABASESTMT 226
#define VNODE_TAG_ALTERDATABASEREFRESHCOLLSTMT 227
#define VNODE_TAG_ALTERDATABASESETSTMT 228
#define VNODE_TAG_DROPDBSTMT 229
#define VNODE_TAG_ALTERSYSTEMSTMT 230
#define VNODE_TAG_CLUSTERSTMT 231
#define VNODE_TAG_VACUUMSTMT 232
#define VNODE_TAG_VACUUMRELATION 233
#define VNODE_TAG_EXPLAINSTMT 234
#define VNODE_TAG_CREATETABLEASSTMT 235
#define VNODE_TAG_REFRESHMATVIEWSTMT 236
#define VNODE_TAG_CHECKPOINTSTMT 237
#define VNODE_TAG_DISCARDSTMT 238
#define VNODE_TAG_LOCKSTMT 239
#define VNODE_TAG_CONSTRAINTSSETSTMT 240
#define VNODE_TAG_REINDEXSTMT 241
#define VNODE_TAG_CREATECONVERSIONSTMT 242
#define VNODE_TAG_CREATECASTSTMT 243
#define VNODE_TAG_CREATETRANSFORMSTMT 244
#define VNODE_TAG_PREPARESTMT 245
#define VNODE_TAG_EXECUTESTMT 246
#define VNODE_TAG_DEALLOCATESTMT 247
#define VNODE_TAG_DROPOWNEDSTMT 248
#define VNODE_TAG_REASSIGNOWNEDSTMT 249
#define VNODE_TAG_ALTERTSDICTIONARYSTMT 250
#define VNODE_TAG_ALTERTSCONFIGURATIONSTMT 251
#define VNODE_TAG_PUBLICATIONTABLE 252
#define VNODE_TAG_PUBLICATIONOBJSPEC 253
#define VNODE_TAG_CREATEPUBLICATIONSTMT 254
#define VNODE_TAG_ALTERPUBLICATIONSTMT 255
#define VNODE_TAG_CREATESUBSCRIPTIONSTMT 256
#define VNODE_TAG_ALTERSUBSCRIPTIONSTMT 257
#define VNODE_TAG_DROPSUBSCRIPTIONSTMT 258
#define VNODE_TAG_INTEGER 259
#define VNODE_TAG_FLOAT 260
#define VNODE_TAG_BOOLEAN 261
#define VNODE_TAG_STRING 262
#define VNODE_TAG_BITSTRING 263
#define VNODE_TAG_LIST 264
#define VNODE_TAG_INTLIST 265
#define VNODE_TAG_OIDLIST 266
#define VNODE_TAG_ACONST 267

struct VNode {
	uint32_t _typ;
	union {
		V_Alias* alias;
		V_RangeVar* range_var;
		V_TableFunc* table_func;
		V_IntoClause* into_clause;
		V_Var* var;
		V_Param* param;
		V_Aggref* aggref;
		V_GroupingFunc* grouping_func;
		V_WindowFunc* window_func;
		V_WindowFuncRunCondition* window_func_run_condition;
		V_MergeSupportFunc* merge_support_func;
		V_SubscriptingRef* subscripting_ref;
		V_FuncExpr* func_expr;
		V_NamedArgExpr* named_arg_expr;
		V_OpExpr* op_expr;
		V_DistinctExpr* distinct_expr;
		V_NullIfExpr* null_if_expr;
		V_ScalarArrayOpExpr* scalar_array_op_expr;
		V_BoolExpr* bool_expr;
		V_SubLink* sub_link;
		V_SubPlan* sub_plan;
		V_AlternativeSubPlan* alternative_sub_plan;
		V_FieldSelect* field_select;
		V_FieldStore* field_store;
		V_RelabelType* relabel_type;
		V_CoerceViaIO* coerce_via_io;
		V_ArrayCoerceExpr* array_coerce_expr;
		V_ConvertRowtypeExpr* convert_rowtype_expr;
		V_CollateExpr* collate_expr;
		V_CaseExpr* case_expr;
		V_CaseWhen* case_when;
		V_CaseTestExpr* case_test_expr;
		V_ArrayExpr* array_expr;
		V_RowExpr* row_expr;
		V_RowCompareExpr* row_compare_expr;
		V_CoalesceExpr* coalesce_expr;
		V_MinMaxExpr* min_max_expr;
		V_SQLValueFunction* sqlvalue_function;
		V_XmlExpr* xml_expr;
		V_JsonFormat* json_format;
		V_JsonReturning* json_returning;
		V_JsonValueExpr* json_value_expr;
		V_JsonConstructorExpr* json_constructor_expr;
		V_JsonIsPredicate* json_is_predicate;
		V_JsonBehavior* json_behavior;
		V_JsonExpr* json_expr;
		V_JsonTablePath* json_table_path;
		V_JsonTablePathScan* json_table_path_scan;
		V_JsonTableSiblingJoin* json_table_sibling_join;
		V_NullTest* null_test;
		V_BooleanTest* boolean_test;
		V_MergeAction* merge_action;
		V_CoerceToDomain* coerce_to_domain;
		V_CoerceToDomainValue* coerce_to_domain_value;
		V_SetToDefault* set_to_default;
		V_CurrentOfExpr* current_of_expr;
		V_NextValueExpr* next_value_expr;
		V_InferenceElem* inference_elem;
		V_TargetEntry* target_entry;
		V_RangeTblRef* range_tbl_ref;
		V_JoinExpr* join_expr;
		V_FromExpr* from_expr;
		V_OnConflictExpr* on_conflict_expr;
		V_Query* query;
		V_TypeName* type_name;
		V_ColumnRef* column_ref;
		V_ParamRef* param_ref;
		V_AExpr* a_expr;
		V_TypeCast* type_cast;
		V_CollateClause* collate_clause;
		V_RoleSpec* role_spec;
		V_FuncCall* func_call;
		V_AStar* a_star;
		V_AIndices* a_indices;
		V_AIndirection* a_indirection;
		V_AArrayExpr* a_array_expr;
		V_ResTarget* res_target;
		V_MultiAssignRef* multi_assign_ref;
		V_SortBy* sort_by;
		V_WindowDef* window_def;
		V_RangeSubselect* range_subselect;
		V_RangeFunction* range_function;
		V_RangeTableFunc* range_table_func;
		V_RangeTableFuncCol* range_table_func_col;
		V_RangeTableSample* range_table_sample;
		V_ColumnDef* column_def;
		V_TableLikeClause* table_like_clause;
		V_IndexElem* index_elem;
		V_DefElem* def_elem;
		V_LockingClause* locking_clause;
		V_XmlSerialize* xml_serialize;
		V_PartitionElem* partition_elem;
		V_PartitionSpec* partition_spec;
		V_PartitionBoundSpec* partition_bound_spec;
		V_PartitionRangeDatum* partition_range_datum;
		V_SinglePartitionSpec* single_partition_spec;
		V_PartitionCmd* partition_cmd;
		V_RangeTblEntry* range_tbl_entry;
		V_RTEPermissionInfo* rtepermission_info;
		V_RangeTblFunction* range_tbl_function;
		V_TableSampleClause* table_sample_clause;
		V_WithCheckOption* with_check_option;
		V_SortGroupClause* sort_group_clause;
		V_GroupingSet* grouping_set;
		V_WindowClause* window_clause;
		V_RowMarkClause* row_mark_clause;
		V_WithClause* with_clause;
		V_InferClause* infer_clause;
		V_OnConflictClause* on_conflict_clause;
		V_CTESearchClause* ctesearch_clause;
		V_CTECycleClause* ctecycle_clause;
		V_CommonTableExpr* common_table_expr;
		V_MergeWhenClause* merge_when_clause;
		V_TriggerTransition* trigger_transition;
		V_JsonOutput* json_output;
		V_JsonArgument* json_argument;
		V_JsonFuncExpr* json_func_expr;
		V_JsonTablePathSpec* json_table_path_spec;
		V_JsonTable* json_table;
		V_JsonTableColumn* json_table_column;
		V_JsonKeyValue* json_key_value;
		V_JsonParseExpr* json_parse_expr;
		V_JsonScalarExpr* json_scalar_expr;
		V_JsonSerializeExpr* json_serialize_expr;
		V_JsonObjectConstructor* json_object_constructor;
		V_JsonArrayConstructor* json_array_constructor;
		V_JsonArrayQueryConstructor* json_array_query_constructor;
		V_JsonAggConstructor* json_agg_constructor;
		V_JsonObjectAgg* json_object_agg;
		V_JsonArrayAgg* json_array_agg;
		V_RawStmt* raw_stmt;
		V_InsertStmt* insert_stmt;
		V_DeleteStmt* delete_stmt;
		V_UpdateStmt* update_stmt;
		V_MergeStmt* merge_stmt;
		V_SelectStmt* select_stmt;
		V_SetOperationStmt* set_operation_stmt;
		V_ReturnStmt* return_stmt;
		V_PLAssignStmt* plassign_stmt;
		V_CreateSchemaStmt* create_schema_stmt;
		V_AlterTableStmt* alter_table_stmt;
		V_ReplicaIdentityStmt* replica_identity_stmt;
		V_AlterTableCmd* alter_table_cmd;
		V_AlterCollationStmt* alter_collation_stmt;
		V_AlterDomainStmt* alter_domain_stmt;
		V_GrantStmt* grant_stmt;
		V_ObjectWithArgs* object_with_args;
		V_AccessPriv* access_priv;
		V_GrantRoleStmt* grant_role_stmt;
		V_AlterDefaultPrivilegesStmt* alter_default_privileges_stmt;
		V_CopyStmt* copy_stmt;
		V_VariableSetStmt* variable_set_stmt;
		V_VariableShowStmt* variable_show_stmt;
		V_CreateStmt* create_stmt;
		V_Constraint* constraint;
		V_CreateTableSpaceStmt* create_table_space_stmt;
		V_DropTableSpaceStmt* drop_table_space_stmt;
		V_AlterTableSpaceOptionsStmt* alter_table_space_options_stmt;
		V_AlterTableMoveAllStmt* alter_table_move_all_stmt;
		V_CreateExtensionStmt* create_extension_stmt;
		V_AlterExtensionStmt* alter_extension_stmt;
		V_AlterExtensionContentsStmt* alter_extension_contents_stmt;
		V_CreateFdwStmt* create_fdw_stmt;
		V_AlterFdwStmt* alter_fdw_stmt;
		V_CreateForeignServerStmt* create_foreign_server_stmt;
		V_AlterForeignServerStmt* alter_foreign_server_stmt;
		V_CreateForeignTableStmt* create_foreign_table_stmt;
		V_CreateUserMappingStmt* create_user_mapping_stmt;
		V_AlterUserMappingStmt* alter_user_mapping_stmt;
		V_DropUserMappingStmt* drop_user_mapping_stmt;
		V_ImportForeignSchemaStmt* import_foreign_schema_stmt;
		V_CreatePolicyStmt* create_policy_stmt;
		V_AlterPolicyStmt* alter_policy_stmt;
		V_CreateAmStmt* create_am_stmt;
		V_CreateTrigStmt* create_trig_stmt;
		V_CreateEventTrigStmt* create_event_trig_stmt;
		V_AlterEventTrigStmt* alter_event_trig_stmt;
		V_CreatePLangStmt* create_plang_stmt;
		V_CreateRoleStmt* create_role_stmt;
		V_AlterRoleStmt* alter_role_stmt;
		V_AlterRoleSetStmt* alter_role_set_stmt;
		V_DropRoleStmt* drop_role_stmt;
		V_CreateSeqStmt* create_seq_stmt;
		V_AlterSeqStmt* alter_seq_stmt;
		V_DefineStmt* define_stmt;
		V_CreateDomainStmt* create_domain_stmt;
		V_CreateOpClassStmt* create_op_class_stmt;
		V_CreateOpClassItem* create_op_class_item;
		V_CreateOpFamilyStmt* create_op_family_stmt;
		V_AlterOpFamilyStmt* alter_op_family_stmt;
		V_DropStmt* drop_stmt;
		V_TruncateStmt* truncate_stmt;
		V_CommentStmt* comment_stmt;
		V_SecLabelStmt* sec_label_stmt;
		V_DeclareCursorStmt* declare_cursor_stmt;
		V_ClosePortalStmt* close_portal_stmt;
		V_FetchStmt* fetch_stmt;
		V_IndexStmt* index_stmt;
		V_CreateStatsStmt* create_stats_stmt;
		V_StatsElem* stats_elem;
		V_AlterStatsStmt* alter_stats_stmt;
		V_CreateFunctionStmt* create_function_stmt;
		V_FunctionParameter* function_parameter;
		V_AlterFunctionStmt* alter_function_stmt;
		V_DoStmt* do_stmt;
		V_InlineCodeBlock* inline_code_block;
		V_CallStmt* call_stmt;
		V_CallContext* call_context;
		V_RenameStmt* rename_stmt;
		V_AlterObjectDependsStmt* alter_object_depends_stmt;
		V_AlterObjectSchemaStmt* alter_object_schema_stmt;
		V_AlterOwnerStmt* alter_owner_stmt;
		V_AlterOperatorStmt* alter_operator_stmt;
		V_AlterTypeStmt* alter_type_stmt;
		V_RuleStmt* rule_stmt;
		V_NotifyStmt* notify_stmt;
		V_ListenStmt* listen_stmt;
		V_UnlistenStmt* unlisten_stmt;
		V_TransactionStmt* transaction_stmt;
		V_CompositeTypeStmt* composite_type_stmt;
		V_CreateEnumStmt* create_enum_stmt;
		V_CreateRangeStmt* create_range_stmt;
		V_AlterEnumStmt* alter_enum_stmt;
		V_ViewStmt* view_stmt;
		V_LoadStmt* load_stmt;
		V_CreatedbStmt* createdb_stmt;
		V_AlterDatabaseStmt* alter_database_stmt;
		V_AlterDatabaseRefreshCollStmt* alter_database_refresh_coll_stmt;
		V_AlterDatabaseSetStmt* alter_database_set_stmt;
		V_DropdbStmt* dropdb_stmt;
		V_AlterSystemStmt* alter_system_stmt;
		V_ClusterStmt* cluster_stmt;
		V_VacuumStmt* vacuum_stmt;
		V_VacuumRelation* vacuum_relation;
		V_ExplainStmt* explain_stmt;
		V_CreateTableAsStmt* create_table_as_stmt;
		V_RefreshMatViewStmt* refresh_mat_view_stmt;
		V_CheckPointStmt* check_point_stmt;
		V_DiscardStmt* discard_stmt;
		V_LockStmt* lock_stmt;
		V_ConstraintsSetStmt* constraints_set_stmt;
		V_ReindexStmt* reindex_stmt;
		V_CreateConversionStmt* create_conversion_stmt;
		V_CreateCastStmt* create_cast_stmt;
		V_CreateTransformStmt* create_transform_stmt;
		V_PrepareStmt* prepare_stmt;
		V_ExecuteStmt* execute_stmt;
		V_DeallocateStmt* deallocate_stmt;
		V_DropOwnedStmt* drop_owned_stmt;
		V_ReassignOwnedStmt* reassign_owned_stmt;
		V_AlterTSDictionaryStmt* alter_tsdictionary_stmt;
		V_AlterTSConfigurationStmt* alter_tsconfiguration_stmt;
		V_PublicationTable* publication_table;
		V_PublicationObjSpec* publication_obj_spec;
		V_CreatePublicationStmt* create_publication_stmt;
		V_AlterPublicationStmt* alter_publication_stmt;
		V_CreateSubscriptionStmt* create_subscription_stmt;
		V_AlterSubscriptionStmt* alter_subscription_stmt;
		V_DropSubscriptionStmt* drop_subscription_stmt;
		V_Integer* integer;
		V_Float* _float;
		V_Boolean* boolean;
		V_String* string;
		V_BitString* bit_string;
		V_List* list;
		V_IntList* int_list;
		V_OidList* oid_list;
		V_AConst* a_const;
	};
};

struct V_Integer {
	int ival;
};

struct V_Float {
	VString fval;
};

struct V_Boolean {
	int boolval;
};

struct V_String {
	VString sval;
};

struct V_BitString {
	VString bsval;
};

struct V_List {
	VArray items;
};

struct V_OidList {
	VArray items;
};

struct V_IntList {
	VArray items;
};

struct V_AConst {
	int isnull;
	int location;
	int ival_state;
	V_Integer ival_data;
	int fval_state;
	V_Float fval_data;
	int boolval_state;
	V_Boolean boolval_data;
	int sval_state;
	V_String sval_data;
	int bsval_state;
	V_BitString bsval_data;
};

struct V_Alias {
	VString aliasname;
	VArray colnames;
};

struct V_TableFunc {
	int functype;
	VArray ns_uris;
	VArray ns_names;
	VNode docexpr;
	VNode rowexpr;
	VArray colnames;
	VArray coltypes;
	VArray coltypmods;
	VArray colcollations;
	VArray colexprs;
	VArray coldefexprs;
	VArray colvalexprs;
	VArray passingvalexprs;
	VArray notnulls;
	VNode plan;
	int ordinalitycol;
	int location;
};

struct V_Var {
	VNode xpr;
	int varno;
	int varattno;
	uint32_t vartype;
	int vartypmod;
	uint32_t varcollid;
	VArray varnullingrels;
	uint32_t varlevelsup;
	int location;
};

struct V_Param {
	VNode xpr;
	int paramkind;
	int paramid;
	uint32_t paramtype;
	int paramtypmod;
	uint32_t paramcollid;
	int location;
};

struct V_Aggref {
	VNode xpr;
	uint32_t aggfnoid;
	uint32_t aggtype;
	uint32_t aggcollid;
	uint32_t inputcollid;
	VArray aggargtypes;
	VArray aggdirectargs;
	VArray args;
	VArray aggorder;
	VArray aggdistinct;
	VNode aggfilter;
	int aggstar;
	int aggvariadic;
	VString aggkind;
	uint32_t agglevelsup;
	int aggsplit;
	int aggno;
	int aggtransno;
	int location;
};

struct V_GroupingFunc {
	VNode xpr;
	VArray args;
	VArray refs;
	uint32_t agglevelsup;
	int location;
};

struct V_WindowFunc {
	VNode xpr;
	uint32_t winfnoid;
	uint32_t wintype;
	uint32_t wincollid;
	uint32_t inputcollid;
	VArray args;
	VNode aggfilter;
	VArray run_condition;
	uint32_t winref;
	int winstar;
	int winagg;
	int location;
};

struct V_WindowFuncRunCondition {
	VNode xpr;
	uint32_t opno;
	uint32_t inputcollid;
	int wfunc_left;
	VNode arg;
};

struct V_MergeSupportFunc {
	VNode xpr;
	uint32_t msftype;
	uint32_t msfcollid;
	int location;
};

struct V_SubscriptingRef {
	VNode xpr;
	uint32_t refcontainertype;
	uint32_t refelemtype;
	uint32_t refrestype;
	int reftypmod;
	uint32_t refcollid;
	VArray refupperindexpr;
	VArray reflowerindexpr;
	VNode refexpr;
	VNode refassgnexpr;
};

struct V_FuncExpr {
	VNode xpr;
	uint32_t funcid;
	uint32_t funcresulttype;
	int funcretset;
	int funcvariadic;
	int funcformat;
	uint32_t funccollid;
	uint32_t inputcollid;
	VArray args;
	int location;
};

struct V_NamedArgExpr {
	VNode xpr;
	VNode arg;
	VString name;
	int argnumber;
	int location;
};

struct V_OpExpr {
	VNode xpr;
	uint32_t opno;
	uint32_t opresulttype;
	int opretset;
	uint32_t opcollid;
	uint32_t inputcollid;
	VArray args;
	int location;
};

struct V_DistinctExpr {
	VNode xpr;
	uint32_t opno;
	uint32_t opresulttype;
	int opretset;
	uint32_t opcollid;
	uint32_t inputcollid;
	VArray args;
	int location;
};

struct V_NullIfExpr {
	VNode xpr;
	uint32_t opno;
	uint32_t opresulttype;
	int opretset;
	uint32_t opcollid;
	uint32_t inputcollid;
	VArray args;
	int location;
};

struct V_ScalarArrayOpExpr {
	VNode xpr;
	uint32_t opno;
	int use_or;
	uint32_t inputcollid;
	VArray args;
	int location;
};

struct V_BoolExpr {
	VNode xpr;
	int boolop;
	VArray args;
	int location;
};

struct V_SubLink {
	VNode xpr;
	int sub_link_type;
	int sub_link_id;
	VNode testexpr;
	VArray oper_name;
	VNode subselect;
	int location;
};

struct V_SubPlan {
	VNode xpr;
	int sub_link_type;
	VNode testexpr;
	VArray param_ids;
	int plan_id;
	VString plan_name;
	uint32_t first_col_type;
	int first_col_typmod;
	uint32_t first_col_collation;
	int use_hash_table;
	int unknown_eq_false;
	int parallel_safe;
	VArray set_param;
	VArray par_param;
	VArray args;
	double startup_cost;
	double per_call_cost;
};

struct V_AlternativeSubPlan {
	VNode xpr;
	VArray subplans;
};

struct V_FieldSelect {
	VNode xpr;
	VNode arg;
	int fieldnum;
	uint32_t resulttype;
	int resulttypmod;
	uint32_t resultcollid;
};

struct V_FieldStore {
	VNode xpr;
	VNode arg;
	VArray newvals;
	VArray fieldnums;
	uint32_t resulttype;
};

struct V_RelabelType {
	VNode xpr;
	VNode arg;
	uint32_t resulttype;
	int resulttypmod;
	uint32_t resultcollid;
	int relabelformat;
	int location;
};

struct V_CoerceViaIO {
	VNode xpr;
	VNode arg;
	uint32_t resulttype;
	uint32_t resultcollid;
	int coerceformat;
	int location;
};

struct V_ArrayCoerceExpr {
	VNode xpr;
	VNode arg;
	VNode elemexpr;
	uint32_t resulttype;
	int resulttypmod;
	uint32_t resultcollid;
	int coerceformat;
	int location;
};

struct V_ConvertRowtypeExpr {
	VNode xpr;
	VNode arg;
	uint32_t resulttype;
	int convertformat;
	int location;
};

struct V_CollateExpr {
	VNode xpr;
	VNode arg;
	uint32_t coll_oid;
	int location;
};

struct V_CaseExpr {
	VNode xpr;
	uint32_t casetype;
	uint32_t casecollid;
	VNode arg;
	VArray args;
	VNode defresult;
	int location;
};

struct V_CaseWhen {
	VNode xpr;
	VNode expr;
	VNode result;
	int location;
};

struct V_CaseTestExpr {
	VNode xpr;
	uint32_t type_id;
	int type_mod;
	uint32_t collation;
};

struct V_ArrayExpr {
	VNode xpr;
	uint32_t array_typeid;
	uint32_t array_collid;
	uint32_t element_typeid;
	VArray elements;
	int multidims;
	int location;
};

struct V_RowExpr {
	VNode xpr;
	VArray args;
	uint32_t row_typeid;
	int row_format;
	VArray colnames;
	int location;
};

struct V_RowCompareExpr {
	VNode xpr;
	int rctype;
	VArray opnos;
	VArray opfamilies;
	VArray inputcollids;
	VArray largs;
	VArray rargs;
};

struct V_CoalesceExpr {
	VNode xpr;
	uint32_t coalescetype;
	uint32_t coalescecollid;
	VArray args;
	int location;
};

struct V_MinMaxExpr {
	VNode xpr;
	uint32_t minmaxtype;
	uint32_t minmaxcollid;
	uint32_t inputcollid;
	int op;
	VArray args;
	int location;
};

struct V_SQLValueFunction {
	VNode xpr;
	int op;
	uint32_t type;
	int typmod;
	int location;
};

struct V_XmlExpr {
	VNode xpr;
	int op;
	VString name;
	VArray named_args;
	VArray arg_names;
	VArray args;
	int xmloption;
	int indent;
	uint32_t type;
	int typmod;
	int location;
};

struct V_JsonFormat {
	int format_type;
	int encoding;
	int location;
};

struct V_JsonBehavior {
	int btype;
	VNode expr;
	int coerce;
	int location;
};

struct V_JsonTablePath {
	VString name;
};

struct V_JsonTableSiblingJoin {
	VNode plan;
	VNode lplan;
	VNode rplan;
};

struct V_NullTest {
	VNode xpr;
	VNode arg;
	int nulltesttype;
	int argisrow;
	int location;
};

struct V_BooleanTest {
	VNode xpr;
	VNode arg;
	int booltesttype;
	int location;
};

struct V_MergeAction {
	int match_kind;
	int command_type;
	int override;
	VNode qual;
	VArray target_list;
	VArray update_colnos;
};

struct V_CoerceToDomain {
	VNode xpr;
	VNode arg;
	uint32_t resulttype;
	int resulttypmod;
	uint32_t resultcollid;
	int coercionformat;
	int location;
};

struct V_CoerceToDomainValue {
	VNode xpr;
	uint32_t type_id;
	int type_mod;
	uint32_t collation;
	int location;
};

struct V_SetToDefault {
	VNode xpr;
	uint32_t type_id;
	int type_mod;
	uint32_t collation;
	int location;
};

struct V_CurrentOfExpr {
	VNode xpr;
	uint32_t cvarno;
	VString cursor_name;
	int cursor_param;
};

struct V_NextValueExpr {
	VNode xpr;
	uint32_t seqid;
	uint32_t type_id;
};

struct V_InferenceElem {
	VNode xpr;
	VNode expr;
	uint32_t infercollid;
	uint32_t inferopclass;
};

struct V_TargetEntry {
	VNode xpr;
	VNode expr;
	int resno;
	VString resname;
	uint32_t ressortgroupref;
	uint32_t resorigtbl;
	int resorigcol;
	int resjunk;
};

struct V_RangeTblRef {
	int rtindex;
};

struct V_FromExpr {
	VArray fromlist;
	VNode quals;
};

struct V_OnConflictExpr {
	int action;
	VArray arbiter_elems;
	VNode arbiter_where;
	uint32_t constraint;
	VArray on_conflict_set;
	VNode on_conflict_where;
	int excl_rel_index;
	VArray excl_rel_tlist;
};

struct V_TypeName {
	VArray names;
	uint32_t type_oid;
	int setof;
	int pct_type;
	VArray typmods;
	int typemod;
	VArray array_bounds;
	int location;
};

struct V_ColumnRef {
	VArray fields;
	int location;
};

struct V_ParamRef {
	int number;
	int location;
};

struct V_AExpr {
	int kind;
	VArray name;
	VNode lexpr;
	VNode rexpr;
	int location;
};

struct V_CollateClause {
	VNode arg;
	VArray collname;
	int location;
};

struct V_RoleSpec {
	int roletype;
	VString rolename;
	int location;
};

struct V_AStar {
};

struct V_AIndices {
	int is_slice;
	VNode lidx;
	VNode uidx;
};

struct V_AIndirection {
	VNode arg;
	VArray indirection;
};

struct V_AArrayExpr {
	VArray elements;
	int location;
};

struct V_ResTarget {
	VString name;
	VArray indirection;
	VNode val;
	int location;
};

struct V_MultiAssignRef {
	VNode source;
	int colno;
	int ncolumns;
};

struct V_SortBy {
	VNode node;
	int sortby_dir;
	int sortby_nulls;
	VArray use_op;
	int location;
};

struct V_WindowDef {
	VString name;
	VString refname;
	VArray partition_clause;
	VArray order_clause;
	int frame_options;
	VNode start_offset;
	VNode end_offset;
	int location;
};

struct V_RangeTableSample {
	VNode relation;
	VArray method;
	VArray args;
	VNode repeatable;
	int location;
};

struct V_IndexElem {
	VString name;
	VNode expr;
	VString indexcolname;
	VArray collation;
	VArray opclass;
	VArray opclassopts;
	int ordering;
	int nulls_ordering;
};

struct V_DefElem {
	VString defnamespace;
	VString defname;
	VNode arg;
	int defaction;
	int location;
};

struct V_LockingClause {
	VArray locked_rels;
	int strength;
	int wait_policy;
};

struct V_PartitionElem {
	VString name;
	VNode expr;
	VArray collation;
	VArray opclass;
	int location;
};

struct V_PartitionSpec {
	int strategy;
	VArray part_params;
	int location;
};

struct V_PartitionBoundSpec {
	VString strategy;
	int is_default;
	int modulus;
	int remainder;
	VArray listdatums;
	VArray lowerdatums;
	VArray upperdatums;
	int location;
};

struct V_PartitionRangeDatum {
	int kind;
	VNode value;
	int location;
};

struct V_SinglePartitionSpec {
};

struct V_RTEPermissionInfo {
	uint32_t relid;
	int inh;
	uint64_t required_perms;
	uint32_t check_as_user;
	VArray selected_cols;
	VArray inserted_cols;
	VArray updated_cols;
};

struct V_RangeTblFunction {
	VNode funcexpr;
	int funccolcount;
	VArray funccolnames;
	VArray funccoltypes;
	VArray funccoltypmods;
	VArray funccolcollations;
	VArray funcparams;
};

struct V_TableSampleClause {
	uint32_t tsmhandler;
	VArray args;
	VNode repeatable;
};

struct V_WithCheckOption {
	int kind;
	VString relname;
	VString polname;
	VNode qual;
	int cascaded;
};

struct V_SortGroupClause {
	uint32_t tle_sort_group_ref;
	uint32_t eqop;
	uint32_t sortop;
	int nulls_first;
	int hashable;
};

struct V_GroupingSet {
	int kind;
	VArray content;
	int location;
};

struct V_WindowClause {
	VString name;
	VString refname;
	VArray partition_clause;
	VArray order_clause;
	int frame_options;
	VNode start_offset;
	VNode end_offset;
	uint32_t start_in_range_func;
	uint32_t end_in_range_func;
	uint32_t in_range_coll;
	int in_range_asc;
	int in_range_nulls_first;
	uint32_t winref;
	int copied_order;
};

struct V_RowMarkClause {
	uint32_t rti;
	int strength;
	int wait_policy;
	int pushed_down;
};

struct V_WithClause {
	VArray ctes;
	int recursive;
	int location;
};

struct V_InferClause {
	VArray index_elems;
	VNode where_clause;
	VString conname;
	int location;
};

struct V_CTESearchClause {
	VArray search_col_list;
	int search_breadth_first;
	VString search_seq_column;
	int location;
};

struct V_CTECycleClause {
	VArray cycle_col_list;
	VString cycle_mark_column;
	VNode cycle_mark_value;
	VNode cycle_mark_default;
	VString cycle_path_column;
	int location;
	uint32_t cycle_mark_type;
	int cycle_mark_typmod;
	uint32_t cycle_mark_collation;
	uint32_t cycle_mark_neop;
};

struct V_MergeWhenClause {
	int match_kind;
	int command_type;
	int override;
	VNode condition;
	VArray target_list;
	VArray values;
};

struct V_TriggerTransition {
	VString name;
	int is_new;
	int is_table;
};

struct V_JsonTablePathSpec {
	VNode string;
	VString name;
	int name_location;
	int location;
};

struct V_RawStmt {
	VNode stmt;
	int stmt_location;
	int stmt_len;
};

struct V_SetOperationStmt {
	int op;
	int all;
	VNode larg;
	VNode rarg;
	VArray col_types;
	VArray col_typmods;
	VArray col_collations;
	VArray group_clauses;
};

struct V_ReturnStmt {
	VNode returnval;
};

struct V_ReplicaIdentityStmt {
	VString identity_type;
	VString name;
};

struct V_AlterCollationStmt {
	VArray collname;
};

struct V_AlterDomainStmt {
	VString subtype;
	VArray type_name;
	VString name;
	VNode def;
	int behavior;
	int missing_ok;
};

struct V_ObjectWithArgs {
	VArray objname;
	VArray objargs;
	VArray objfuncargs;
	int args_unspecified;
};

struct V_AccessPriv {
	VString priv_name;
	VArray cols;
};

struct V_VariableSetStmt {
	int kind;
	VString name;
	VArray args;
	int is_local;
};

struct V_VariableShowStmt {
	VString name;
};

struct V_DropTableSpaceStmt {
	VString tablespacename;
	int missing_ok;
};

struct V_AlterTableSpaceOptionsStmt {
	VString tablespacename;
	VArray options;
	int is_reset;
};

struct V_AlterTableMoveAllStmt {
	VString orig_tablespacename;
	int objtype;
	VArray roles;
	VString new_tablespacename;
	int nowait;
};

struct V_CreateExtensionStmt {
	VString extname;
	int if_not_exists;
	VArray options;
};

struct V_AlterExtensionStmt {
	VString extname;
	VArray options;
};

struct V_AlterExtensionContentsStmt {
	VString extname;
	int action;
	int objtype;
	VNode object;
};

struct V_CreateFdwStmt {
	VString fdwname;
	VArray func_options;
	VArray options;
};

struct V_AlterFdwStmt {
	VString fdwname;
	VArray func_options;
	VArray options;
};

struct V_CreateForeignServerStmt {
	VString servername;
	VString servertype;
	VString version;
	VString fdwname;
	int if_not_exists;
	VArray options;
};

struct V_AlterForeignServerStmt {
	VString servername;
	VString version;
	VArray options;
	int has_version;
};

struct V_ImportForeignSchemaStmt {
	VString server_name;
	VString remote_schema;
	VString local_schema;
	int list_type;
	VArray table_list;
	VArray options;
};

struct V_CreateAmStmt {
	VString amname;
	VArray handler_name;
	VString amtype;
};

struct V_CreateEventTrigStmt {
	VString trigname;
	VString eventname;
	VArray whenclause;
	VArray funcname;
};

struct V_AlterEventTrigStmt {
	VString trigname;
	VString tgenabled;
};

struct V_CreatePLangStmt {
	int replace;
	VString plname;
	VArray plhandler;
	VArray plinline;
	VArray plvalidator;
	int pltrusted;
};

struct V_CreateRoleStmt {
	int stmt_type;
	VString role;
	VArray options;
};

struct V_DropRoleStmt {
	VArray roles;
	int missing_ok;
};

struct V_DefineStmt {
	int kind;
	int oldstyle;
	VArray defnames;
	VArray args;
	VArray definition;
	int if_not_exists;
	int replace;
};

struct V_CreateOpFamilyStmt {
	VArray opfamilyname;
	VString amname;
};

struct V_AlterOpFamilyStmt {
	VArray opfamilyname;
	VString amname;
	int is_drop;
	VArray items;
};

struct V_DropStmt {
	VArray objects;
	int remove_type;
	int behavior;
	int missing_ok;
	int concurrent;
};

struct V_TruncateStmt {
	VArray relations;
	int restart_seqs;
	int behavior;
};

struct V_CommentStmt {
	int objtype;
	VNode object;
	VString comment;
};

struct V_SecLabelStmt {
	int objtype;
	VNode object;
	VString provider;
	VString label;
};

struct V_DeclareCursorStmt {
	VString portalname;
	int options;
	VNode query;
};

struct V_ClosePortalStmt {
	VString portalname;
};

struct V_FetchStmt {
	int direction;
	int64_t how_many;
	VString portalname;
	int ismove;
};

struct V_CreateStatsStmt {
	VArray defnames;
	VArray stat_types;
	VArray exprs;
	VArray relations;
	VString stxcomment;
	int transformed;
	int if_not_exists;
};

struct V_StatsElem {
	VString name;
	VNode expr;
};

struct V_AlterStatsStmt {
	VArray defnames;
	VNode stxstattarget;
	int missing_ok;
};

struct V_DoStmt {
	VArray args;
};

struct V_InlineCodeBlock {
	VString source_text;
	uint32_t lang_oid;
	int lang_is_trusted;
	int atomic;
};

struct V_CallContext {
	int atomic;
};

struct V_AlterTypeStmt {
	VArray type_name;
	VArray options;
};

struct V_NotifyStmt {
	VString conditionname;
	VString payload;
};

struct V_ListenStmt {
	VString conditionname;
};

struct V_UnlistenStmt {
	VString conditionname;
};

struct V_TransactionStmt {
	int kind;
	VArray options;
	VString savepoint_name;
	VString gid;
	int chain;
	int location;
};

struct V_CreateEnumStmt {
	VArray type_name;
	VArray vals;
};

struct V_CreateRangeStmt {
	VArray type_name;
	VArray params;
};

struct V_AlterEnumStmt {
	VArray type_name;
	VString old_val;
	VString new_val;
	VString new_val_neighbor;
	int new_val_is_after;
	int skip_if_new_val_exists;
};

struct V_LoadStmt {
	VString filename;
};

struct V_CreatedbStmt {
	VString dbname;
	VArray options;
};

struct V_AlterDatabaseStmt {
	VString dbname;
	VArray options;
};

struct V_AlterDatabaseRefreshCollStmt {
	VString dbname;
};

struct V_DropdbStmt {
	VString dbname;
	int missing_ok;
	VArray options;
};

struct V_VacuumStmt {
	VArray options;
	VArray rels;
	int is_vacuumcmd;
};

struct V_ExplainStmt {
	VNode query;
	VArray options;
};

struct V_CheckPointStmt {
};

struct V_DiscardStmt {
	int target;
};

struct V_LockStmt {
	VArray relations;
	int mode;
	int nowait;
};

struct V_ConstraintsSetStmt {
	VArray constraints;
	int deferred;
};

struct V_CreateConversionStmt {
	VArray conversion_name;
	VString for_encoding_name;
	VString to_encoding_name;
	VArray func_name;
	int def;
};

struct V_PrepareStmt {
	VString name;
	VArray argtypes;
	VNode query;
};

struct V_ExecuteStmt {
	VString name;
	VArray params;
};

struct V_DeallocateStmt {
	VString name;
	int isall;
	int location;
};

struct V_DropOwnedStmt {
	VArray roles;
	int behavior;
};

struct V_AlterTSDictionaryStmt {
	VArray dictname;
	VArray options;
};

struct V_AlterTSConfigurationStmt {
	int kind;
	VArray cfgname;
	VArray tokentype;
	VArray dicts;
	int override;
	int replace;
	int missing_ok;
};

struct V_CreatePublicationStmt {
	VString pubname;
	VArray options;
	VArray pubobjects;
	int for_all_tables;
};

struct V_AlterPublicationStmt {
	VString pubname;
	VArray options;
	VArray pubobjects;
	int for_all_tables;
	int action;
};

struct V_CreateSubscriptionStmt {
	VString subname;
	VString conninfo;
	VArray publication;
	VArray options;
};

struct V_AlterSubscriptionStmt {
	int kind;
	VString subname;
	VString conninfo;
	VArray publication;
	VArray options;
};

struct V_DropSubscriptionStmt {
	VString subname;
	int missing_ok;
	int behavior;
};

struct V_ScanToken {
	int start;
	int end;
	int token;
	int keyword_kind;
};

struct V_RangeVar {
	VString catalogname;
	VString schemaname;
	VString relname;
	int inh;
	VString relpersistence;
	V_Alias alias;
	int location;
};

struct V_JoinExpr {
	int jointype;
	int is_natural;
	VNode larg;
	VNode rarg;
	VArray using_clause;
	V_Alias join_using_alias;
	VNode quals;
	V_Alias alias;
	int rtindex;
};

struct V_RangeSubselect {
	int lateral;
	VNode subquery;
	V_Alias alias;
};

struct V_RangeFunction {
	int lateral;
	int ordinality;
	int is_rowsfrom;
	VArray functions;
	V_Alias alias;
	VArray coldeflist;
};

struct V_RangeTableFunc {
	int lateral;
	VNode docexpr;
	VNode rowexpr;
	VArray namespaces;
	VArray columns;
	V_Alias alias;
	int location;
};

struct V_JsonReturning {
	V_JsonFormat format;
	uint32_t typid;
	int typmod;
};

struct V_JsonValueExpr {
	VNode raw_expr;
	VNode formatted_expr;
	V_JsonFormat format;
};

struct V_JsonIsPredicate {
	VNode expr;
	V_JsonFormat format;
	int item_type;
	int unique_keys;
	int location;
};

struct V_JsonTablePathScan {
	VNode plan;
	V_JsonTablePath path;
	int error_on_error;
	VNode child;
	int col_min;
	int col_max;
};

struct V_Query {
	int command_type;
	int query_source;
	int can_set_tag;
	VNode utility_stmt;
	int result_relation;
	int has_aggs;
	int has_window_funcs;
	int has_target_srfs;
	int has_sub_links;
	int has_distinct_on;
	int has_recursive;
	int has_modifying_cte;
	int has_for_update;
	int has_row_security;
	int is_return;
	VArray cte_list;
	VArray rtable;
	VArray rteperminfos;
	V_FromExpr jointree;
	VArray merge_action_list;
	int merge_target_relation;
	VNode merge_join_condition;
	VArray target_list;
	int override;
	V_OnConflictExpr on_conflict;
	VArray returning_list;
	VArray group_clause;
	int group_distinct;
	VArray grouping_sets;
	VNode having_qual;
	VArray window_clause;
	VArray distinct_clause;
	VArray sort_clause;
	VNode limit_offset;
	VNode limit_count;
	int limit_option;
	VArray row_marks;
	VNode set_operations;
	VArray constraint_deps;
	VArray with_check_options;
	int stmt_location;
	int stmt_len;
};

struct V_TypeCast {
	VNode arg;
	V_TypeName type_name;
	int location;
};

struct V_RangeTableFuncCol {
	VString colname;
	V_TypeName type_name;
	int for_ordinality;
	int is_not_null;
	VNode colexpr;
	VNode coldefexpr;
	int location;
};

struct V_XmlSerialize {
	int xmloption;
	VNode expr;
	V_TypeName type_name;
	int indent;
	int location;
};

struct V_CreateOpClassStmt {
	VArray opclassname;
	VArray opfamilyname;
	VString amname;
	V_TypeName datatype;
	VArray items;
	int is_default;
};

struct V_CreateFunctionStmt {
	int is_procedure;
	int replace;
	VArray funcname;
	VArray parameters;
	V_TypeName return_type;
	VArray options;
	VNode sql_body;
};

struct V_FunctionParameter {
	VString name;
	V_TypeName arg_type;
	int mode;
	VNode defexpr;
};

struct V_CreateDomainStmt {
	VArray domainname;
	V_TypeName type_name;
	V_CollateClause coll_clause;
	VArray constraints;
};

struct V_CreateSchemaStmt {
	VString schemaname;
	V_RoleSpec authrole;
	VArray schema_elts;
	int if_not_exists;
};

struct V_AlterTableCmd {
	int subtype;
	VString name;
	int num;
	V_RoleSpec newowner;
	VNode def;
	int behavior;
	int missing_ok;
	int recurse;
};

struct V_GrantStmt {
	int is_grant;
	int targtype;
	int objtype;
	VArray objects;
	VArray privileges;
	VArray grantees;
	int grant_option;
	V_RoleSpec grantor;
	int behavior;
};

struct V_GrantRoleStmt {
	VArray granted_roles;
	VArray grantee_roles;
	int is_grant;
	VArray opt;
	V_RoleSpec grantor;
	int behavior;
};

struct V_CreateTableSpaceStmt {
	VString tablespacename;
	V_RoleSpec owner;
	VString location;
	VArray options;
};

struct V_CreateUserMappingStmt {
	V_RoleSpec user;
	VString servername;
	int if_not_exists;
	VArray options;
};

struct V_AlterUserMappingStmt {
	V_RoleSpec user;
	VString servername;
	VArray options;
};

struct V_DropUserMappingStmt {
	V_RoleSpec user;
	VString servername;
	int missing_ok;
};

struct V_AlterRoleStmt {
	V_RoleSpec role;
	VArray options;
	int action;
};

struct V_ReassignOwnedStmt {
	VArray roles;
	V_RoleSpec newrole;
};

struct V_FuncCall {
	VArray funcname;
	VArray args;
	VArray agg_order;
	VNode agg_filter;
	V_WindowDef over;
	int agg_within_group;
	int agg_star;
	int agg_distinct;
	int func_variadic;
	int funcformat;
	int location;
};

struct V_OnConflictClause {
	int action;
	V_InferClause infer;
	VArray target_list;
	VNode where_clause;
	int location;
};

struct V_CommonTableExpr {
	VString ctename;
	VArray aliascolnames;
	int ctematerialized;
	VNode ctequery;
	V_CTESearchClause search_clause;
	V_CTECycleClause cycle_clause;
	int location;
	int cterecursive;
	int cterefcount;
	VArray ctecolnames;
	VArray ctecoltypes;
	VArray ctecoltypmods;
	VArray ctecolcollations;
};

struct V_JsonTableColumn {
	int coltype;
	VString name;
	V_TypeName type_name;
	V_JsonTablePathSpec pathspec;
	V_JsonFormat format;
	int wrapper;
	int quotes;
	VArray columns;
	V_JsonBehavior on_empty;
	V_JsonBehavior on_error;
	int location;
};

struct V_CreateOpClassItem {
	int itemtype;
	V_ObjectWithArgs name;
	int number;
	VArray order_family;
	VArray class_args;
	V_TypeName storedtype;
};

struct V_AlterFunctionStmt {
	int objtype;
	V_ObjectWithArgs func;
	VArray actions;
};

struct V_AlterOperatorStmt {
	V_ObjectWithArgs opername;
	VArray options;
};

struct V_CreateCastStmt {
	V_TypeName sourcetype;
	V_TypeName targettype;
	V_ObjectWithArgs func;
	int context;
	int inout;
};

struct V_CreateTransformStmt {
	int replace;
	V_TypeName type_name;
	VString lang;
	V_ObjectWithArgs fromsql;
	V_ObjectWithArgs tosql;
};

struct V_AlterRoleSetStmt {
	V_RoleSpec role;
	VString database;
	V_VariableSetStmt setstmt;
};

struct V_AlterDatabaseSetStmt {
	VString dbname;
	V_VariableSetStmt setstmt;
};

struct V_AlterSystemStmt {
	V_VariableSetStmt setstmt;
};

struct V_IntoClause {
	V_RangeVar rel;
	VArray col_names;
	VString access_method;
	VArray options;
	int on_commit;
	VString table_space_name;
	VNode view_query;
	int skip_data;
};

struct V_ColumnDef {
	VString colname;
	V_TypeName type_name;
	VString compression;
	int inhcount;
	int is_local;
	int is_not_null;
	int is_from_type;
	VString storage;
	VString storage_name;
	VNode raw_default;
	VNode cooked_default;
	VString identity;
	V_RangeVar identity_sequence;
	VString generated;
	V_CollateClause coll_clause;
	uint32_t coll_oid;
	VArray constraints;
	VArray fdwoptions;
	int location;
};

struct V_TableLikeClause {
	V_RangeVar relation;
	uint32_t options;
	uint32_t relation_oid;
};

struct V_PartitionCmd {
	V_RangeVar name;
	V_PartitionBoundSpec bound;
	int concurrent;
};

struct V_DeleteStmt {
	V_RangeVar relation;
	VArray using_clause;
	VNode where_clause;
	VArray returning_list;
	V_WithClause with_clause;
};

struct V_UpdateStmt {
	V_RangeVar relation;
	VArray target_list;
	VNode where_clause;
	VArray from_clause;
	VArray returning_list;
	V_WithClause with_clause;
};

struct V_MergeStmt {
	V_RangeVar relation;
	VNode source_relation;
	VNode join_condition;
	VArray merge_when_clauses;
	VArray returning_list;
	V_WithClause with_clause;
};

struct V_AlterTableStmt {
	V_RangeVar relation;
	VArray cmds;
	int objtype;
	int missing_ok;
};

struct V_CopyStmt {
	V_RangeVar relation;
	VNode query;
	VArray attlist;
	int is_from;
	int is_program;
	VString filename;
	VArray options;
	VNode where_clause;
};

struct V_CreateStmt {
	V_RangeVar relation;
	VArray table_elts;
	VArray inh_relations;
	V_PartitionBoundSpec partbound;
	V_PartitionSpec partspec;
	V_TypeName of_typename;
	VArray constraints;
	VArray options;
	int oncommit;
	VString tablespacename;
	VString access_method;
	int if_not_exists;
};

struct V_Constraint {
	int contype;
	VString conname;
	int deferrable;
	int initdeferred;
	int skip_validation;
	int initially_valid;
	int is_no_inherit;
	VNode raw_expr;
	VString cooked_expr;
	VString generated_when;
	int inhcount;
	int nulls_not_distinct;
	VArray keys;
	VArray including;
	VArray exclusions;
	VArray options;
	VString indexname;
	VString indexspace;
	int reset_default_tblspc;
	VString access_method;
	VNode where_clause;
	V_RangeVar pktable;
	VArray fk_attrs;
	VArray pk_attrs;
	VString fk_matchtype;
	VString fk_upd_action;
	VString fk_del_action;
	VArray fk_del_set_cols;
	VArray old_conpfeqop;
	uint32_t old_pktable_oid;
	int location;
};

struct V_CreatePolicyStmt {
	VString policy_name;
	V_RangeVar table;
	VString cmd_name;
	int permissive;
	VArray roles;
	VNode qual;
	VNode with_check;
};

struct V_AlterPolicyStmt {
	VString policy_name;
	V_RangeVar table;
	VArray roles;
	VNode qual;
	VNode with_check;
};

struct V_CreateTrigStmt {
	int replace;
	int isconstraint;
	VString trigname;
	V_RangeVar relation;
	VArray funcname;
	VArray args;
	int row;
	int timing;
	int events;
	VArray columns;
	VNode when_clause;
	VArray transition_rels;
	int deferrable;
	int initdeferred;
	V_RangeVar constrrel;
};

struct V_CreateSeqStmt {
	V_RangeVar sequence;
	VArray options;
	uint32_t owner_id;
	int for_identity;
	int if_not_exists;
};

struct V_AlterSeqStmt {
	V_RangeVar sequence;
	VArray options;
	int for_identity;
	int missing_ok;
};

struct V_IndexStmt {
	VString idxname;
	V_RangeVar relation;
	VString access_method;
	VString table_space;
	VArray index_params;
	VArray index_including_params;
	VArray options;
	VNode where_clause;
	VArray exclude_op_names;
	VString idxcomment;
	uint32_t index_oid;
	uint32_t old_number;
	uint32_t old_create_subid;
	uint32_t old_first_relfilelocator_subid;
	int unique;
	int nulls_not_distinct;
	int primary;
	int isconstraint;
	int deferrable;
	int initdeferred;
	int transformed;
	int concurrent;
	int if_not_exists;
	int reset_default_tblspc;
};

struct V_RenameStmt {
	int rename_type;
	int relation_type;
	V_RangeVar relation;
	VNode object;
	VString subname;
	VString newname;
	int behavior;
	int missing_ok;
};

struct V_AlterObjectDependsStmt {
	int object_type;
	V_RangeVar relation;
	VNode object;
	V_String extname;
	int remove;
};

struct V_AlterObjectSchemaStmt {
	int object_type;
	V_RangeVar relation;
	VNode object;
	VString newschema;
	int missing_ok;
};

struct V_AlterOwnerStmt {
	int object_type;
	V_RangeVar relation;
	VNode object;
	V_RoleSpec newowner;
};

struct V_RuleStmt {
	V_RangeVar relation;
	VString rulename;
	VNode where_clause;
	int event;
	int instead;
	VArray actions;
	int replace;
};

struct V_CompositeTypeStmt {
	V_RangeVar typevar;
	VArray coldeflist;
};

struct V_ViewStmt {
	V_RangeVar view;
	VArray aliases;
	VNode query;
	int replace;
	VArray options;
	int with_check_option;
};

struct V_ClusterStmt {
	V_RangeVar relation;
	VString indexname;
	VArray params;
};

struct V_VacuumRelation {
	V_RangeVar relation;
	uint32_t oid;
	VArray va_cols;
};

struct V_RefreshMatViewStmt {
	int concurrent;
	int skip_data;
	V_RangeVar relation;
};

struct V_ReindexStmt {
	int kind;
	V_RangeVar relation;
	VString name;
	VArray params;
};

struct V_PublicationTable {
	V_RangeVar relation;
	VNode where_clause;
	VArray columns;
};

struct V_JsonConstructorExpr {
	VNode xpr;
	int type;
	VArray args;
	VNode func;
	VNode coercion;
	V_JsonReturning returning;
	int absent_on_null;
	int unique;
	int location;
};

struct V_JsonExpr {
	VNode xpr;
	int op;
	VString column_name;
	VNode formatted_expr;
	V_JsonFormat format;
	VNode path_spec;
	V_JsonReturning returning;
	VArray passing_names;
	VArray passing_values;
	V_JsonBehavior on_empty;
	V_JsonBehavior on_error;
	int use_io_coercion;
	int use_json_coercion;
	int wrapper;
	int omit_quotes;
	uint32_t collation;
	int location;
};

struct V_JsonOutput {
	V_TypeName type_name;
	V_JsonReturning returning;
};

struct V_JsonArgument {
	V_JsonValueExpr val;
	VString name;
};

struct V_JsonTable {
	V_JsonValueExpr context_item;
	V_JsonTablePathSpec pathspec;
	VArray passing;
	VArray columns;
	V_JsonBehavior on_error;
	V_Alias alias;
	int lateral;
	int location;
};

struct V_JsonKeyValue {
	VNode key;
	V_JsonValueExpr value;
};

struct V_RangeTblEntry {
	V_Alias alias;
	V_Alias eref;
	int rtekind;
	uint32_t relid;
	int inh;
	VString relkind;
	int rellockmode;
	uint32_t perminfoindex;
	V_TableSampleClause tablesample;
	V_Query subquery;
	int security_barrier;
	int jointype;
	int joinmergedcols;
	VArray joinaliasvars;
	VArray joinleftcols;
	VArray joinrightcols;
	V_Alias join_using_alias;
	VArray functions;
	int funcordinality;
	V_TableFunc tablefunc;
	VArray values_lists;
	VString ctename;
	uint32_t ctelevelsup;
	int self_reference;
	VArray coltypes;
	VArray coltypmods;
	VArray colcollations;
	VString enrname;
	double enrtuples;
	int lateral;
	int in_from_cl;
	VArray security_quals;
};

struct V_AlterDefaultPrivilegesStmt {
	VArray options;
	V_GrantStmt action;
};

struct V_CallStmt {
	V_FuncCall funccall;
	V_FuncExpr funcexpr;
	VArray outargs;
};

struct V_InsertStmt {
	V_RangeVar relation;
	VArray cols;
	VNode select_stmt;
	V_OnConflictClause on_conflict_clause;
	VArray returning_list;
	V_WithClause with_clause;
	int override;
};

struct V_SelectStmt {
	VArray distinct_clause;
	V_IntoClause into_clause;
	VArray target_list;
	VArray from_clause;
	VNode where_clause;
	VArray group_clause;
	int group_distinct;
	VNode having_clause;
	VArray window_clause;
	VArray values_lists;
	VArray sort_clause;
	VNode limit_offset;
	VNode limit_count;
	int limit_option;
	VArray locking_clause;
	V_WithClause with_clause;
	int op;
	int all;
	struct V_SelectStmt* larg;
	struct V_SelectStmt* rarg;
};

struct V_CreateTableAsStmt {
	VNode query;
	V_IntoClause into;
	int objtype;
	int is_select_into;
	int if_not_exists;
};

struct V_CreateForeignTableStmt {
	V_CreateStmt base_stmt;
	VString servername;
	VArray options;
};

struct V_PublicationObjSpec {
	int pubobjtype;
	VString name;
	V_PublicationTable pubtable;
	int location;
};

struct V_JsonFuncExpr {
	int op;
	VString column_name;
	V_JsonValueExpr context_item;
	VNode pathspec;
	VArray passing;
	V_JsonOutput output;
	V_JsonBehavior on_empty;
	V_JsonBehavior on_error;
	int wrapper;
	int quotes;
	int location;
};

struct V_JsonParseExpr {
	V_JsonValueExpr expr;
	V_JsonOutput output;
	int unique_keys;
	int location;
};

struct V_JsonScalarExpr {
	VNode expr;
	V_JsonOutput output;
	int location;
};

struct V_JsonSerializeExpr {
	V_JsonValueExpr expr;
	V_JsonOutput output;
	int location;
};

struct V_JsonObjectConstructor {
	VArray exprs;
	V_JsonOutput output;
	int absent_on_null;
	int unique;
	int location;
};

struct V_JsonArrayConstructor {
	VArray exprs;
	V_JsonOutput output;
	int absent_on_null;
	int location;
};

struct V_JsonArrayQueryConstructor {
	VNode query;
	V_JsonOutput output;
	V_JsonFormat format;
	int absent_on_null;
	int location;
};

struct V_JsonAggConstructor {
	V_JsonOutput output;
	VNode agg_filter;
	VArray agg_order;
	V_WindowDef over;
	int location;
};

struct V_PLAssignStmt {
	VString name;
	VArray indirection;
	int nnames;
	V_SelectStmt val;
	int location;
};

struct V_JsonObjectAgg {
	V_JsonAggConstructor constructor;
	V_JsonKeyValue arg;
	int absent_on_null;
	int unique;
};

struct V_JsonArrayAgg {
	V_JsonAggConstructor constructor;
	V_JsonValueExpr arg;
	int absent_on_null;
};

struct V_ParseAstResult {
	int version;
	VArray stmts;
};

#endif /* PG_QUERY_AST_C_H */
